export {default as Login } from "./Login/Login"
export {default as Register } from "./Register/Register"
export {default as Home } from "./Home/Home"
export {default as Lesson } from "./Lesson/Lesson"
export {default as Result } from "./Result/Result"
export {default as NotFound } from "./NotFound/NotFound"
export {default as Quiz } from "./Quiz/Quiz"
